### ISSUE TITLE
Operation 'toAbsolutePath' is not supported by QuiltPath

### ISSUE THREAD

**Issue by wosmanitx** [quiltdata/nf-quilt#104]
When attempting to reference a directory such as:

mzML_folder = quilt+s3://interline-proteomics-analysis#package=TechDev/DIANN_APMS_demo@1357028e5391f8153647d13771d221536f90d1699b99e913bd29162379ff1d27&path=mzML_files%2F

I get this error:

Operation 'toAbsolutePath' is not supported by QuiltPath

**Comment by drernie** [comment]
Are you still seeing this error?
