### ISSUE TITLE
Reduce debug logging

### ISSUE THREAD

**Issue by drernie** [quiltdata/nf-quilt#116]
We don't need ALL this debugging information.  Mainly just:
- which Quilt URIs are used for input and output
- the exact quilt3 commands
- whether things succeed

**Comment by drernie** [comment]
Convert non-fatal errors to warnings

**Comment by theJasonFan** [comment]
Hi! Thanks for the plugin!

FWIW there's also this one here: https://github.com/quiltdata/nf-quilt/blob/9eaf13c41e13fcf9f066664f1df709bb42b2048c/plugins/nf-quilt/src/main/nextflow/quilt/jep/QuiltPackage.groovy#L198

I think this error gets hit whenever a new package is created. Tracing the path in the source, `setup()` is called here https://github.com/quiltdata/nf-quilt/blob/9eaf13c41e13fcf9f066664f1df709bb42b2048c/plugins/nf-quilt/src/main/nextflow/quilt/jep/QuiltPackage.groovy#L125 and `setup()` calls `install()`.

**Comment by drernie** [comment]
Thanks. this is causing issues in both directions.  I will try to wrangle it down next week.

**Comment by drernie** [comment]
Seems resolved

**Comment by drernie** [comment]
@theJasonFan If you are still seeing issues, please try to reproduce with 0.8.6 or later

```
# export NXF_VER=23.04.3
export LOG4J_DEBUG=true  # for verbose logging
export NXF_PLUGINS_TEST_REPOSITORY=https://github.com/quiltdata/nf-quilt/releases/download/0.8.6/nf-quilt-0.8.6-meta.json
nextflow run main.nf -plugins nf-quilt@0.8.6
```

**Comment by theJasonFan** [comment]
@drernie Thanks for closing the issue. If I run into this issue again I will try to reproduce.
