### ISSUE TITLE
Cannot test nf-core/sarek due to nf-validation

### ISSUE THREAD

**Issue by drernie** [quiltdata/nf-quilt#147]
I have been using sarek to validate that nf-quilt works with real-world pipelines.
But now I've been getting:

```
./launch.sh run nf-core/sarek -profile test,docker -plugins nf-quilt --outdir "quilt+s3://quilt-ernest-staging#package=nf-quilt/sarek"
N E X T F L O W  ~  version 23.06.0-edge
Launching `https://github.com/nf-core/sarek` [distracted_monod] DSL2 - revision: f034b73763 [master]
installing nf-quilt/sarek from quilt-ernest-staging...
hash: null -> 1f6869169484fcdf0d67cf8354b97fdcdc15b68f6472c50bd3ea24ba2f3abe21
done
ERROR ~ Install is not supported on dev mode - Missing plugin nf-validation 
```

Do I need to do something different with newer versions of `nextflow`?

**Comment by bentsherman** [comment]
When you run Nextflow in dev mode using `launch.sh` it is not possible to load non-core plugins like nf-validation. You would have to add nf-validation to your nf-qulit build which sounds quite hairy.

What I like to do in this situation, if you don't actually need to change the Nextflow source code, is to install your plugin locally and run it with `nextflow`. Here's how I do it for nf-prov: https://github.com/nextflow-io/nf-prov/blob/2e88da839fc769de82e28f34100e0ae9cd8ed90a/Makefile#L46-L49

At some point I will try to document it better

**Comment by drernie** [comment]
Ah, excellent. And running `nextflow` from anywhere will automatically find $HOME/.nextflow/plugins?

**Comment by drernie** [comment]
That worked! Thank you so much.
