### ISSUE TITLE
[verify] Customize commit message via query (metadata)

### ISSUE THREAD

**Issue by drernie** [quiltdata/nf-quilt#43]
1. Extract metadata from query
2. Push with package
3. Use some key like 'msg' to create the commit message

**Comment by drernie** [comment]
More generally:

How do we want to configure the created package?

Can we infer a README and quilt_summarize from appropriate conventions? Eg HTML reports

**Comment by wosmanitx** [comment]
yes, modifying the readme and defining the quilt summarize would be great features.

**Comment by drernie** [comment]
Thanks. I'm curious: how would you want to do that?

Some options off the top of my head:

1. Writing out the actual files during your pipeline run
2. Creating "template" files (stored where?) which nf-quilt uses by filling in various parameters
3. Embedding "callbacks" in your Groovy scripts that nf-quilt uses to generate the files

**Comment by drernie** [comment]
@wosmanitx This is now available live in 0.3.5, via query parameters:
- commit_message
- readme

Let me know if this works, or you need something else!

**Comment by drernie** [comment]
Should work.
