### ISSUE TITLE
rethink NextFlow dependency

### ISSUE THREAD

**Issue by drernie** [quiltdata/nf-quilt#57]
There are a several different environments our potential users might have:

1. Already have the NextFlow executable in place
2. Already have the NextFlow repo in place
3. Already have Java and need NextFlow
4. Need Java as well as NextFlow

**Comment by drernie** [comment]
I don't think there's any easy way to automate Java installs (4), but we could:
- autodetect NextFlow (executable or repo)
- use that if present
- install it automatically if not

Same with the quilt3 dependency.

Not sure if it is worth the effort, if most people are using Tower.
Also, the breaking change to publish in NextFlow 23.x makes using an existing version somewhat fraught.

**Comment by bentsherman** [comment]
For users, it should be enough to tell them to install Nextflow and point to the Nextflow docs: https://nextflow.io/docs/latest/getstarted.html

For developers, they need to clone this repo and the Nextflow repo, and they need Java to build and test everything.

The thing is that there are some nuances to picking the right Java version. Ideally, the Nextflow docs will maintain the best guidance for how to install Java. Currently a work in progress: https://github.com/nextflow-io/nextflow/pull/3617

If people are being introduced to Nextflow/Tower through this Quilt plugin, their first step should be to install Nextflow locally or create a Tower account. The plugin will only be some extra configuration in their workflow run.

**Comment by drernie** [comment]
I added a little bit about Java under Development; that should suffice:

> If this is your first time using NextFlow, you may to first need to install a recent 
[version of Java](https://www.java.com/en/download/help/download_options.html) for your platform.
NextFlow itself will take care of all the other dependencies.
